-- ============================================================================
-- V1__baseline.sql  —  WordAI baseline schema
-- ============================================================================
-- Applied to *fresh* databases only (tests, new environments).
-- Existing production databases are tracked via spring.flyway.baseline-on-migrate=true,
-- which marks V1 as already applied without executing this script.
--
-- See: docs/features/flyway-schema-migration.spec.md
-- ============================================================================

-- --------------------------------------------------------------------------
-- Table: users
-- JPA entity: com.fistraltech.security.model.User
-- --------------------------------------------------------------------------
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    username    VARCHAR(255),
    password    VARCHAR(255),
    full_name   VARCHAR(255),
    provider    VARCHAR(255),
    provider_id VARCHAR(255),
    created_at  TIMESTAMP(6),
    last_login  TIMESTAMP(6),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_users_email    UNIQUE (email),
    CONSTRAINT uq_users_username UNIQUE (username)
);

-- --------------------------------------------------------------------------
-- Table: user_roles
-- JPA: User.roles (@ElementCollection)
-- --------------------------------------------------------------------------
CREATE TABLE user_roles (
    user_id BIGINT      NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- --------------------------------------------------------------------------
-- Table: player_games
-- JPA entity: com.fistraltech.server.model.PersistedGame
-- --------------------------------------------------------------------------
CREATE TABLE player_games (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    game_id         VARCHAR(50)  NOT NULL,
    target_word     VARCHAR(20)  NOT NULL,
    word_length     INTEGER,
    dictionary_id   VARCHAR(50),
    guess_words     VARCHAR(500),
    guess_responses VARCHAR(500),
    result          VARCHAR(10)  NOT NULL,
    attempts_used   INTEGER,
    max_attempts    INTEGER,
    completed_at    TIMESTAMP(6) NOT NULL
);
